### ISSUE TITLE
Can't load tool with latest version of XrmToolBox

### ISSUE THREAD

**Issue by BetimBeja** [jamesnovak/Futurez.XrmToolBox.PortalDependencies#3]
The following error is shown when trying to open the tool.
<img width="313" alt="image" src="https://github.com/jamesnovak/Futurez.XrmToolBox.PortalDependencies/assets/11160171/14c1061d-b6d3-411e-810a-30f41f0ada6b">

**Comment by BetimBeja** [comment]
<img width="974" alt="image" src="https://github.com/jamesnovak/Futurez.XrmToolBox.PortalDependencies/assets/11160171/eda5ab0d-beb6-4914-93ab-d64bc305614e">


```
System.Exception
  HResult=0x80131500
  Message=Cannot find the control parent. Try to use the method HideNotification only when the control is loaded
  Source=XrmToolBox.Extensibility
  StackTrace:
   at XrmToolBox.Extensibility.PluginControlBase.HideNotification()
   at Futurez.XrmToolBox.PortalDependenciesControl.UpdatePortalsInstallMessage() in D:\repos\Betim Beja\Futurez.XrmToolBox.PortalDependencies\PortalDependenciesControl.cs:line 1093
   at Futurez.XrmToolBox.PortalDependenciesControl.UpdateConnection(IOrganizationService newService, ConnectionDetail detail, String actionName, Object parameter) in D:\repos\Betim Beja\Futurez.XrmToolBox.PortalDependencies\PortalDependenciesControl.cs:line 285
   at XrmToolBox.New.NewForm.DisplayPluginControl(Lazy`2 plugin, Boolean displayConnected)
```

**Comment by rbouchetdxc** [comment]
I am currently using the latest version of XRM Toolbox, and have just installed this tool, and am currently getting this error

![Image](https://github.com/user-attachments/assets/d09ead7b-25c6-48e0-9468-cf7131d81547)

![Image](https://github.com/user-attachments/assets/a7726ebb-00e3-4e11-a4cb-ef8e8971ee19)
